In [130]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)

In [203]:
customers_df = pd.read_csv("olist_customers_dataset.csv")
orders_df = pd.read_csv("olist_orders_dataset.csv")
order_items_df = pd.read_csv("olist_order_items_dataset.csv")
payments_df = pd.read_csv("olist_order_payments_dataset.csv")
reviews_df = pd.read_csv("olist_order_reviews_dataset.csv")
products_df = pd.read_csv("olist_products_dataset.csv")
sellers_df = pd.read_csv("olist_sellers_dataset.csv")
geo_df = pd.read_csv("olist_geolocation_dataset.csv")
category_translation_df = pd.read_csv("product_category_name_translation.csv")

In [132]:
datasets = {
    "Customers": customers_df,
    "Orders": orders_df,
    "Order Items": order_items_df,
    "Payments": payments_df,
    "Reviews": reviews_df,
    "Products": products_df,
    "Sellers": sellers_df,
    "Geolocation": geo_df,
    "Translation": translation_df
}

In [133]:
for name, df in datasets.items():
    print("=" * 70)
    print(name.upper())
    print("=" * 70)

    print("\nShape:", df.shape)

    print("\nColumns:")
    print(df.columns.tolist())

    print("\nData Types:")
    print(df.dtypes)

    print("\nFirst Five Rows:")
    display(df.head())

======================================================================
CUSTOMERS
======================================================================

Shape: (99441, 5)

Columns:
['customer_id', 'customer_unique_id', 'customer_zip_code_prefix', 'customer_city', 'customer_state']

Data Types:
customer_id                 object
customer_unique_id          object
customer_zip_code_prefix     int64
customer_city               object
customer_state              object
dtype: object

First Five Rows:

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP

======================================================================
ORDERS
======================================================================

Shape: (99441, 8)

Columns:
['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp', 'order_approved_at', 'order_delivered_carrier_date', 'order_delivered_customer_date', 'order_estimated_delivery_date']

Data Types:
order_id                         object
customer_id                      object
order_status                     object
order_purchase_timestamp         object
order_approved_at                object
order_delivered_carrier_date     object
order_delivered_customer_date    object
order_estimated_delivery_date    object
dtype: object

First Five Rows:

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00

======================================================================
ORDER ITEMS
======================================================================

Shape: (112650, 7)

Columns:
['order_id', 'order_item_id', 'product_id', 'seller_id', 'shipping_limit_date', 'price', 'freight_value']

Data Types:
order_id                object
order_item_id            int64
product_id              object
seller_id               object
shipping_limit_date     object
price                  float64
freight_value          float64
dtype: object

First Five Rows:

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14

======================================================================
PAYMENTS
======================================================================

Shape: (103886, 5)

Columns:
['order_id', 'payment_sequential', 'payment_type', 'payment_installments', 'payment_value']

Data Types:
order_id                 object
payment_sequential        int64
payment_type             object
payment_installments      int64
payment_value           float64
dtype: object

First Five Rows:

,order_id,payment_sequential,payment_type,payment_installments,payment_value
0,b81ef226f3fe1789b1e8b2acac839d17,1,credit_card,8,99.33
1,a9810da82917af2d9aefd1278f1dcfa0,1,credit_card,1,24.39
2,25e8ea4e93396b6fa0d3dd708e76c1bd,1,credit_card,1,65.71
3,ba78997921bbcdc1373bb41e913ab953,1,credit_card,8,107.78
4,42fdf880ba16b47b59251dd489d4441a,1,credit_card,2,128.45

======================================================================
REVIEWS
======================================================================

Shape: (99224, 7)

Columns:
['review_id', 'order_id', 'review_score', 'review_comment_title', 'review_comment_message', 'review_creation_date', 'review_answer_timestamp']

Data Types:
review_id                  object
order_id                   object
review_score                int64
review_comment_title       object
review_comment_message     object
review_creation_date       object
review_answer_timestamp    object
dtype: object

First Five Rows:

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,NaN,NaN,2018-01-18 00:00:00,2018-01-18 21:46:59
1,80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,NaN,NaN,2018-03-10 00:00:00,2018-03-11 03:05:13
2,228ce5500dc1d8e020d8d1322874b6f0,f9e4b658b201a9f2ecdecbb34bed034b,5,NaN,NaN,2018-02-17 00:00:00,2018-02-18 14:36:24
3,e64fb393e7b32834bb789ff8bb30750e,658677c97b385a9be170737859d3511b,5,NaN,Recebi bem antes do prazo estipulado.,2017-04-21 00:00:00,2017-04-21 22:02:06
4,f7c4243c7fe1938f181bec41a392bdeb,8e6bfb81e283fa7e4f11123a3fb894f1,5,NaN,Parabéns lojas lannister adorei comprar pela I...,2018-03-01 00:00:00,2018-03-02 10:26:53

======================================================================
PRODUCTS
======================================================================

Shape: (32951, 9)

Columns:
['product_id', 'product_category_name', 'product_name_lenght', 'product_description_lenght', 'product_photos_qty', 'product_weight_g', 'product_length_cm', 'product_height_cm', 'product_width_cm']

Data Types:
product_id                     object
product_category_name          object
product_name_lenght           float64
product_description_lenght    float64
product_photos_qty            float64
product_weight_g              float64
product_length_cm             float64
product_height_cm             float64
product_width_cm              float64
dtype: object

First Five Rows:

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.0,261.0,1.0,371.0,26.0,4.0,26.0
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,402.0,4.0,625.0,20.0,17.0,13.0

======================================================================
SELLERS
======================================================================

Shape: (3095, 4)

Columns:
['seller_id', 'seller_zip_code_prefix', 'seller_city', 'seller_state']

Data Types:
seller_id                 object
seller_zip_code_prefix     int64
seller_city               object
seller_state              object
dtype: object

First Five Rows:

,seller_id,seller_zip_code_prefix,seller_city,seller_state
0,3442f8959a84dea7ee197c632cb2df15,13023,campinas,SP
1,d1b65fc7debc3361ea86b5f14c68d2e2,13844,mogi guacu,SP
2,ce3ad9de960102d0677a81f5d0bb7b2d,20031,rio de janeiro,RJ
3,c0f3eea2e14555b6faeea3dd58c1b1c3,4195,sao paulo,SP
4,51a04a8a6bdcb23deccc82b0b80742cf,12914,braganca paulista,SP

======================================================================
GEOLOCATION
======================================================================

Shape: (1000163, 5)

Columns:
['geolocation_zip_code_prefix', 'geolocation_lat', 'geolocation_lng', 'geolocation_city', 'geolocation_state']

Data Types:
geolocation_zip_code_prefix      int64
geolocation_lat                float64
geolocation_lng                float64
geolocation_city                object
geolocation_state               object
dtype: object

First Five Rows:

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
0,1037,-23.545621,-46.639292,sao paulo,SP
1,1046,-23.546081,-46.644820,sao paulo,SP
2,1046,-23.546129,-46.642951,sao paulo,SP
3,1041,-23.544392,-46.639499,sao paulo,SP
4,1035,-23.541578,-46.641607,sao paulo,SP

======================================================================
TRANSLATION
======================================================================

Shape: (71, 2)

Columns:
['product_category_name', 'product_category_name_english']

Data Types:
product_category_name            object
product_category_name_english    object
dtype: object

First Five Rows:

    product_category_name product_category_name_english
0            beleza_saude                 health_beauty
1  informatica_acessorios         computers_accessories
2              automotivo                          auto
3         cama_mesa_banho                bed_bath_table
4        moveis_decoracao               furniture_decor

In [134]:
customers_df.head()

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP

In [135]:
customers_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 5 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               99441 non-null  object
 1   customer_unique_id        99441 non-null  object
 2   customer_zip_code_prefix  99441 non-null  int64
 3   customer_city             99441 non-null  object
 4   customer_state            99441 non-null  object
dtypes: int64(1), object(4)
memory usage: 3.8+ MB

In [136]:
customers_df.describe(include ="all")

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
count,99441,99441,99441.000000,99441,99441
unique,99441,96096,NaN,4119,27
top,274fa6071e5e17fe303b9748641082c8,8d50f5eadf50201ccdcedfb9e2ac8455,NaN,sao paulo,SP
freq,1,17,NaN,15540,41746
mean,NaN,NaN,35137.474583,NaN,NaN
std,NaN,NaN,29797.938996,NaN,NaN
min,NaN,NaN,1003.000000,NaN,NaN
25%,NaN,NaN,11347.000000,NaN,NaN
50%,NaN,NaN,24416.000000,NaN,NaN
75%,NaN,NaN,58900.000000,NaN,NaN
max,NaN,NaN,99990.000000,NaN,NaN

In [137]:
customers_df.isnull().sum()

customer_id                 0
customer_unique_id          0
customer_zip_code_prefix    0
customer_city               0
customer_state              0
dtype: int64

In [138]:
customers_df.duplicated().sum()

np.int64(0)

In [139]:
customers_df.nunique()

customer_id                 99441
customer_unique_id          96096
customer_zip_code_prefix    14994
customer_city                4119
customer_state                 27
dtype: int64

orders

In [140]:
orders_df.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00

In [141]:
orders_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  object
 1   customer_id                    99441 non-null  object
 2   order_status                   99441 non-null  object
 3   order_purchase_timestamp       99441 non-null  object
 4   order_approved_at              99281 non-null  object
 5   order_delivered_carrier_date   97658 non-null  object
 6   order_delivered_customer_date  96476 non-null  object
 7   order_estimated_delivery_date  99441 non-null  object
dtypes: object(8)
memory usage: 6.1+ MB

In [142]:
orders_df.describe(include ="all")

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
count,99441,99441,99441,99441,99281,97658,96476,99441
unique,99441,99441,8,98875,90733,81018,95664,459
top,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,delivered,2018-08-02 12:06:07,2018-02-27 04:31:10,2018-05-09 15:48:00,2018-05-14 20:02:44,2017-12-20 00:00:00
freq,1,1,96478,3,9,47,3,522

In [143]:
orders_df.isnull().sum()

order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64

In [144]:
orders_df.duplicated().sum()

np.int64(0)

In [145]:
orders_df.groupby("order_status")[[
    "order_approved_at",
    "order_delivered_carrier_date",
    "order_delivered_customer_date"
]].apply(lambda x: x.isnull().sum())

,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date
order_status,,,
approved,0,2,2
canceled,141,550,619
created,5,5,5
delivered,14,2,8
invoiced,0,314,314
processing,0,301,301
shipped,0,0,1107
unavailable,0,609,609

The missing values in the timestamp columns are not random.

After analyzing the `order_status` column, it was observed that these NULL values mainly belong to orders with statuses such as:

• canceled
• unavailable
• created
• processing/approved (orders not yet delivered)

Since these orders never reached later stages of the order lifecycle, the missing timestamps are expected and represent valid business information rather than data quality issues.

In [146]:
# converting to datetime variable

date_columns = [
    "order_purchase_timestamp",
    "order_approved_at",
    "order_delivered_carrier_date",
    "order_delivered_customer_date",
    "order_estimated_delivery_date"
]

for col in date_columns:
    orders_df[col] = pd.to_datetime(orders_df[col])

In [147]:
orders_df.dtypes

order_id                                 object
customer_id                              object
order_status                             object
order_purchase_timestamp         datetime64[ns]
order_approved_at                datetime64[ns]
order_delivered_carrier_date     datetime64[ns]
order_delivered_customer_date    datetime64[ns]
order_estimated_delivery_date    datetime64[ns]
dtype: object

In [148]:
# monthly sales
orders_df['order_purchase_timestamp'].dt.month

0        10
1         7
2         8
3        11
4         2
         ..
99436     3
99437     2
99438     8
99439     1
99440     3
Name: order_purchase_timestamp, Length: 99441, dtype: int32

In [149]:
# yearly sales
orders_df['order_purchase_timestamp'].dt.year

0        2017
1        2018
2        2018
3        2017
4        2018
         ...
99436    2017
99437    2018
99438    2017
99439    2018
99440    2018
Name: order_purchase_timestamp, Length: 99441, dtype: int32

In [150]:
# day vice sales
orders_df['order_purchase_timestamp'].dt.day_name()

0           Monday
1          Tuesday
2        Wednesday
3         Saturday
4          Tuesday
           ...
99436     Thursday
99437      Tuesday
99438       Sunday
99439       Monday
99440     Thursday
Name: order_purchase_timestamp, Length: 99441, dtype: object

In [151]:
orders_df['order_purchase_timestamp'].dt.hour

0        10
1        20
2         8
3        19
4        21
         ..
99436     9
99437    12
99438    14
99439    21
99440    20
Name: order_purchase_timestamp, Length: 99441, dtype: int32

In [152]:
# quaterly sales
orders_df['order_purchase_timestamp'].dt.quarter

0        4
1        3
2        3
3        4
4        1
        ..
99436    1
99437    1
99438    3
99439    1
99440    1
Name: order_purchase_timestamp, Length: 99441, dtype: int32

### Feature Engineering

In [153]:
orders_df["purchase_year"] = (
    orders_df["order_purchase_timestamp"].dt.year
)

In [154]:
orders_df["purchase_month"] = (
    orders_df["order_purchase_timestamp"].dt.month
)

In [155]:
orders_df["purchase_month_name"] = (
    orders_df["order_purchase_timestamp"].dt.month_name()
)

In [156]:
orders_df["purchase_day"] = (
    orders_df["order_purchase_timestamp"].dt.day
)

In [157]:
orders_df["purchase_weekday"] = (
    orders_df["order_purchase_timestamp"].dt.day_name()
)

In [158]:
orders_df["purchase_hour"] = (
    orders_df["order_purchase_timestamp"].dt.hour
)

In [159]:
orders_df["purchase_quarter"] = (
    orders_df["order_purchase_timestamp"].dt.quarter
)

In [160]:
# delivery timeline very imp for business perspective

orders_df["delivery_time_days"] = (
    orders_df["order_delivered_customer_date"]
    - orders_df["order_purchase_timestamp"]
).dt.days

In [161]:
# delivery delay
orders_df["delivery_delay_days"] = (
    orders_df["order_delivered_customer_date"]
    - orders_df["order_estimated_delivery_date"]
).dt.days

In [162]:
orders_df[
    [
        "purchase_year",
        "purchase_month_name",
        "purchase_weekday",
        "purchase_hour",
        "delivery_time_days",
        "delivery_delay_days",
    ]
].head()

,purchase_year,purchase_month_name,purchase_weekday,purchase_hour,delivery_time_days,delivery_delay_days
0,2017,October,Monday,10,8.0,-8.0
1,2018,July,Tuesday,20,13.0,-6.0
2,2018,August,Wednesday,8,9.0,-18.0
3,2017,November,Saturday,19,13.0,-13.0
4,2018,February,Tuesday,21,2.0,-10.0

# Phase 3: Data Quality Report

In [163]:
# this function is used to quality check the data

def data_quality_report(df):
    report = pd.DataFrame({
        "Column": df.columns,
        "Data Type": df.dtypes.values,
        "Missing Values": df.isnull().sum().values,
        "Missing %": ((df.isnull().sum()/len(df))*100).round(2).values,
        "Unique Values": df.nunique().values
    })

    return report

In [164]:
data_quality_report(customers_df)

,Column,Data Type,Missing Values,Missing %,Unique Values
0,customer_id,object,0,0.0,99441
1,customer_unique_id,object,0,0.0,96096
2,customer_zip_code_prefix,int64,0,0.0,14994
3,customer_city,object,0,0.0,4119
4,customer_state,object,0,0.0,27

In [165]:
data_quality_report(orders_df)

,Column,Data Type,Missing Values,Missing %,Unique Values
0,order_id,object,0,0.00,99441
1,customer_id,object,0,0.00,99441
2,order_status,object,0,0.00,8
3,order_purchase_timestamp,datetime64[ns],0,0.00,98875
4,order_approved_at,datetime64[ns],160,0.16,90733
5,order_delivered_carrier_date,datetime64[ns],1783,1.79,81018
6,order_delivered_customer_date,datetime64[ns],2965,2.98,95664
7,order_estimated_delivery_date,datetime64[ns],0,0.00,459
8,purchase_year,int32,0,0.00,3
9,purchase_month,int32,0,0.00,12
10,purchase_month_name,object,0,0.00,12
11,purchase_day,int32,0,0.00,31
12,purchase_weekday,object,0,0.00,7
13,purchase_hour,int32,0,0.00,24
14,purchase_quarter,int32,0,0.00,4
15,delivery_time_days,float64,2965,2.98,146
16,delivery_delay_days,float64,2965,2.98,198

In [166]:
data_quality_report(order_items_df)

                Column Data Type  Missing Values  Missing %  Unique Values
0             order_id    object               0        0.0          98666
1        order_item_id     int64               0        0.0             21
2           product_id    object               0        0.0          32951
3            seller_id    object               0        0.0           3095
4  shipping_limit_date    object               0        0.0          93318
5                price   float64               0        0.0           5968
6        freight_value   float64               0        0.0           6999

In [167]:
data_quality_report(payments_df)

                 Column Data Type  Missing Values  Missing %  Unique Values
0              order_id    object               0        0.0          99440
1    payment_sequential     int64               0        0.0             29
2          payment_type    object               0        0.0              5
3  payment_installments     int64               0        0.0             24
4         payment_value   float64               0        0.0          29077

In [168]:
data_quality_report(reviews_df)

                    Column Data Type  Missing Values  Missing %  Unique Values
0                review_id    object               0       0.00          98410
1                 order_id    object               0       0.00          98673
2             review_score     int64               0       0.00              5
3     review_comment_title    object           87656      88.34           4527
4   review_comment_message    object           58247      58.70          36159
5     review_creation_date    object               0       0.00            636
6  review_answer_timestamp    object               0       0.00          98248

In [169]:
data_quality_report(products_df)

,Column,Data Type,Missing Values,Missing %,Unique Values
0,product_id,object,0,0.00,32951
1,product_category_name,object,610,1.85,73
2,product_name_lenght,float64,610,1.85,66
3,product_description_lenght,float64,610,1.85,2960
4,product_photos_qty,float64,610,1.85,19
5,product_weight_g,float64,2,0.01,2204
6,product_length_cm,float64,2,0.01,99
7,product_height_cm,float64,2,0.01,102
8,product_width_cm,float64,2,0.01,95

In [170]:
data_quality_report(sellers_df)

                   Column Data Type  Missing Values  Missing %  Unique Values
0               seller_id    object               0        0.0           3095
1  seller_zip_code_prefix     int64               0        0.0           2246
2             seller_city    object               0        0.0            611
3            seller_state    object               0        0.0             23

In [171]:
data_quality_report(geo_df)

,Column,Data Type,Missing Values,Missing %,Unique Values
0,geolocation_zip_code_prefix,int64,0,0.0,19015
1,geolocation_lat,float64,0,0.0,717360
2,geolocation_lng,float64,0,0.0,717613
3,geolocation_city,object,0,0.0,8011
4,geolocation_state,object,0,0.0,27

In [172]:
data_quality_report(translation_df)

,Column,Data Type,Missing Values,Missing %,Unique Values
0,product_category_name,object,0,0.0,71
1,product_category_name_english,object,0,0.0,71

## Missing Value Assessment

The missing values were classified into three categories:

1. Business Missing
   - Occur because of the business process.
   - Example: Delivery timestamps for cancelled orders.
   - Decision: Retained.

2. Optional Missing
   - Fields that users are not required to fill.
   - Example: Review comments.
   - Decision: Retained.

3. Data Quality Missing
   - Missing due to incomplete or incorrect data.
   - Example: Product dimensions.
   - Decision: To be investigated and handled appropriately.

In [173]:
reviews_df.head(10)

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,NaN,NaN,2018-01-18 00:00:00,2018-01-18 21:46:59
1,80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,NaN,NaN,2018-03-10 00:00:00,2018-03-11 03:05:13
2,228ce5500dc1d8e020d8d1322874b6f0,f9e4b658b201a9f2ecdecbb34bed034b,5,NaN,NaN,2018-02-17 00:00:00,2018-02-18 14:36:24
3,e64fb393e7b32834bb789ff8bb30750e,658677c97b385a9be170737859d3511b,5,NaN,Recebi bem antes do prazo estipulado.,2017-04-21 00:00:00,2017-04-21 22:02:06
4,f7c4243c7fe1938f181bec41a392bdeb,8e6bfb81e283fa7e4f11123a3fb894f1,5,NaN,Parabéns lojas lannister adorei comprar pela I...,2018-03-01 00:00:00,2018-03-02 10:26:53
5,15197aa66ff4d0650b5434f1b46cda19,b18dcdf73be66366873cd26c5724d1dc,1,NaN,NaN,2018-04-13 00:00:00,2018-04-16 00:39:37
6,07f9bee5d1b850860defd761afa7ff16,e48aa0d2dcec3a2e87348811bcfdf22b,5,NaN,NaN,2017-07-16 00:00:00,2017-07-18 19:30:34
7,7c6400515c67679fbee952a7525281ef,c31a859e34e3adac22f376954e19b39d,5,NaN,NaN,2018-08-14 00:00:00,2018-08-14 21:36:06
8,a3f6f7f6f433de0aefbb97da197c554c,9c214ac970e84273583ab523dfafd09b,5,NaN,NaN,2017-05-17 00:00:00,2017-05-18 12:05:37
9,8670d52e15e00043ae7de4c01cc2fe06,b9bf720beb4ab3728760088589c62129,4,recomendo,aparelho eficiente. no site a marca do aparelh...,2018-05-22 00:00:00,2018-05-23 16:45:47

In [174]:
reviews_df.sample(10)

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
69410,a752bded6938927fe475e3be46cfaca6,203a651bc28694f332b40c3e61bf8e04,5,NaN,excelente custo/benefício.,2018-01-11 00:00:00,2018-01-11 22:27:19
93601,f290bcabcb4d849440049bba3eebc55f,090d3784ef3038b64220941aa370584b,5,NaN,"Chegou muito antes do previsto, e minha filha ...",2017-10-03 00:00:00,2017-10-06 18:11:52
58977,1a35992dca7b906158ea4b5cd05b9291,b8a4cbf978ddb7ef0264c480a122329f,5,NaN,Chegou tudo certo e correto,2017-02-01 00:00:00,2017-02-01 19:08:13
6500,102e8d1ceaee3e0774a037615651a5dc,5fd51001358a7987c0e38d1d74a610ea,5,NaN,NaN,2018-05-24 00:00:00,2018-05-26 22:47:56
52995,8a24de8190b2938850f35024877ce8bf,bedc87ce363e6bf8c8868b96b2213ae4,5,NaN,Ótimo produto! Recomendo!!!!,2018-03-10 00:00:00,2018-03-12 13:38:49
28631,1b8da481a54dbaa0890eaaabbb16f8a8,772bb5d1c259f2731fb87d079c3808f0,5,super recomendo,"ótimo produto, entrega no prazo, gosto muito d...",2018-08-11 00:00:00,2018-08-14 12:33:41
36864,69fd4c76e65288be8ec9e1193b651357,d17fc99c6e3eefd9ab2694dadbd05943,1,NaN,Pedi 2 vidros de 1000 l de forth cobre e 1 de ...,2017-11-25 00:00:00,2017-11-29 22:29:19
85915,84bdf8998389a051604a8dde7c90ffdb,cf8ceeefc490504b4e117676aabb2820,5,NaN,Ótimo produto. De acordo com o anúncio. Entreg...,2018-02-07 00:00:00,2018-02-07 15:43:36
56729,3c9b27aa40915ba046299462c4a92290,b6cc7bff663bc68317b27e915be941ca,5,NaN,NaN,2018-05-18 00:00:00,2018-05-20 19:42:16
82862,4fbe5b7fa603dd1c5fa8fe479f864bf5,a6f118bcb8721211afbb36e4a1e63610,5,Ótima,NaN,2018-08-19 00:00:00,2018-08-19 22:24:52

In [175]:
products_df.head(10)

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.0,261.0,1.0,371.0,26.0,4.0,26.0
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,402.0,4.0,625.0,20.0,17.0,13.0
5,41d3672d4792049fa1779bb35283ed13,instrumentos_musicais,60.0,745.0,1.0,200.0,38.0,5.0,11.0
6,732bd381ad09e530fe0a5f457d81becb,cool_stuff,56.0,1272.0,4.0,18350.0,70.0,24.0,44.0
7,2548af3e6e77a690cf3eb6368e9ab61e,moveis_decoracao,56.0,184.0,2.0,900.0,40.0,8.0,40.0
8,37cc742be07708b53a98702e77a21a02,eletrodomesticos,57.0,163.0,1.0,400.0,27.0,13.0,17.0
9,8c92109888e8cdf9d66dc7e463025574,brinquedos,36.0,1156.0,1.0,600.0,17.0,10.0,12.0

In [176]:
products_df.sample(10)

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
10568,d14b123540fc5edbd4b0fbc48102a6c4,papelaria,56.0,599.0,2.0,175.0,18.0,14.0,22.0
12684,10a3a969b9e7d03b0dc2384ebbcad6ef,automotivo,48.0,670.0,5.0,23350.0,64.0,64.0,51.0
6908,e1559fbf98a69c9a54d3df4c359aa164,cama_mesa_banho,53.0,495.0,1.0,650.0,30.0,3.0,19.0
31957,46a280e88b01f31141fbe4db92370286,utilidades_domesticas,56.0,1210.0,1.0,2050.0,30.0,30.0,30.0
29130,fed7ed9a2c9239558d696bfb40fc96a9,telefonia,30.0,843.0,1.0,125.0,16.0,10.0,13.0
14142,47ef5dcb5b7bf6d8716ec362e1f6e22b,esporte_lazer,59.0,757.0,5.0,1100.0,20.0,10.0,20.0
29771,5d790355cbeded0cd60e25cbc4c527a2,informatica_acessorios,38.0,225.0,1.0,115.0,16.0,13.0,11.0
22552,aee6a26e6b45a1c262018c8bb3125848,esporte_lazer,53.0,651.0,1.0,2500.0,27.0,32.0,39.0
16853,ee473bd1ca4e671eafbcb7453d7d7c5f,esporte_lazer,46.0,1549.0,1.0,17650.0,60.0,42.0,42.0
20623,5dffc90ad9125991a7ba68cb88c2233d,artigos_de_natal,39.0,265.0,1.0,600.0,16.0,19.0,14.0

In [177]:
products_df.tail(10)

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
32941,6ec96c91757fad0aecafc0ee7f262dcc,bebes,62.0,1417.0,1.0,9550.0,36.0,35.0,35.0
32942,16280ca280a86fee2ba3c928ed04439f,moveis_decoracao,64.0,236.0,11.0,2200.0,31.0,11.0,26.0
32943,3becff10d1deb92b02f2a1ee62a04524,informatica_acessorios,54.0,1520.0,2.0,6150.0,30.0,30.0,20.0
32944,1a14237ecc2fe3772b55c8d4e11ccb35,moveis_decoracao,58.0,1405.0,3.0,150.0,35.0,2.0,25.0
32945,c4e71b64511b959455e2107fe7859020,utilidades_domesticas,59.0,1371.0,2.0,200.0,18.0,15.0,15.0
32946,a0b7d5a992ccda646f2d34e418fff5a0,moveis_decoracao,45.0,67.0,2.0,12300.0,40.0,40.0,40.0
32947,bf4538d88321d0fd4412a93c974510e6,construcao_ferramentas_iluminacao,41.0,971.0,1.0,1700.0,16.0,19.0,16.0
32948,9a7c6041fa9592d9d9ef6cfe62a71f8c,cama_mesa_banho,50.0,799.0,1.0,1400.0,27.0,7.0,27.0
32949,83808703fc0706a22e264b9d75f04a2e,informatica_acessorios,60.0,156.0,2.0,700.0,31.0,13.0,20.0
32950,106392145fca363410d287a815be6de4,cama_mesa_banho,58.0,309.0,1.0,2083.0,12.0,2.0,7.0

In [178]:
# Filter condition
null_filter = products_df.isnull().any(axis=1)

# Apply the filter to view the data
products_df[null_filter]

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
105,a41e356c76fab66334f36de622ecbd3a,NaN,NaN,NaN,NaN,650.0,17.0,14.0,12.0
128,d8dee61c2034d6d075997acef1870e9b,NaN,NaN,NaN,NaN,300.0,16.0,7.0,20.0
145,56139431d72cd51f19eb9f7dae4d1617,NaN,NaN,NaN,NaN,200.0,20.0,20.0,20.0
154,46b48281eb6d663ced748f324108c733,NaN,NaN,NaN,NaN,18500.0,41.0,30.0,41.0
197,5fb61f482620cb672f5e586bb132eae9,NaN,NaN,NaN,NaN,300.0,35.0,7.0,12.0
...,...,...,...,...,...,...,...,...,...
32515,b0a0c5dd78e644373b199380612c350a,NaN,NaN,NaN,NaN,1800.0,30.0,20.0,70.0
32589,10dbe0fbaa2c505123c17fdc34a63c56,NaN,NaN,NaN,NaN,800.0,30.0,10.0,23.0
32616,bd2ada37b58ae94cc838b9c0569fecd8,NaN,NaN,NaN,NaN,200.0,21.0,8.0,16.0
32772,fa51e914046aab32764c41356b9d4ea4,NaN,NaN,NaN,NaN,1300.0,45.0,16.0,45.0
32852,c4ceee876c82b8328e9c293fa0e1989b,NaN,NaN,NaN,NaN,700.0,28.0,3.0,43.0

| Table    | Column              | Missing Type     | Decision              | Reason                                         |
| -------- | ------------------- | ---------------- | --------------------- | ---------------------------------------------- |
| Orders   | Delivery timestamps | Business Missing | Keep NULL             | Order never reached that stage                 |
| Reviews  | Comment Title       | Optional Missing | Keep NULL             | Customer gave only a rating                    |
| Reviews  | Comment Message     | Optional Missing | Keep NULL             | Customer gave only a rating                    |
| Products | Category            | Data Quality     | Fill with `"Unknown"` | Makes category analysis and dashboards clearer |
| Products | Weight              | Data Quality     | Keep NULL             | Cannot infer accurately                        |
| Products | Dimensions          | Data Quality     | Keep NULL             | Avoid introducing incorrect data               |
| Products | Description/Photos  | Data Quality     | Keep NULL             | Not critical for our planned analysis          |

In [179]:
customers_df.columns

Index(['customer_id', 'customer_unique_id', 'customer_zip_code_prefix',
       'customer_city', 'customer_state'],
      dtype='object')

# Relation between the table

                    Customers
                        │
                        │
                        ▼
                   ORDERS ⭐
              /      |      \
             /       |       \
            ▼        ▼        ▼
      Payments   Reviews   Order Items
                               │
                        ┌──────┴──────┐
                        ▼             ▼
                   Products      Sellers
                        │
                        ▼
              Category Translation

In [180]:
reviews_df.groupby("order_id")["review_id"].count().sort_values(ascending=False).head()

order_id
03c939fd7fd3b38f8485a0f95798f1f6    3
c88b1d1b157a9999ce368f218a407141    3
8e17072ec97ce29f0e1f111e598b0c85    3
df56136b8031ecd28e200bb18e6ddb2e    3
075a544c5f4ed4bb75f82b160465fe76    2
Name: review_id, dtype: int64

Why did you verify the relationships before merging?"

"Before joining the tables, I validated the cardinality using the data rather than relying solely on documentation. This helped identify one-to-many relationships that could duplicate records during joins. By understanding the relationships first, I was able to choose the correct merge strategy and avoid incorrect business metrics."

In [181]:
# orders if our fact table so want to keep every record of it so we are using left join and orders_df as our left table

analytics_df = orders_df.merge(
    customers_df,
    on="customer_id",
    how="left"
)

In [182]:
print("Rows:", analytics_df.shape[0])

print("Columns:", analytics_df.shape[1])

print("Duplicates:", analytics_df.duplicated().sum())

print("Missing Values:")
print(analytics_df.isnull().sum())

Rows: 99441
Columns: 21
Duplicates: 0
Missing Values:
order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
purchase_year                       0
purchase_month                      0
purchase_month_name                 0
purchase_day                        0
purchase_weekday                    0
purchase_hour                       0
purchase_quarter                    0
delivery_time_days               2965
delivery_delay_days              2965
customer_unique_id                  0
customer_zip_code_prefix            0
customer_city                       0
customer_state                      0
dtype: int64

In [183]:
analytics_df = analytics_df.merge(
    order_items_df,
    on = "order_id",
    how = "left",
    validate="one_to_many"
    )

In [184]:
print("="*50)
print("MERGE VALIDATION")
print("="*50)

print(f"Rows: {analytics_df.shape[0]}")
print(f"Columns: {analytics_df.shape[1]}")

print(f"\nUnique Orders: {analytics_df['order_id'].nunique()}")

print(f"Duplicate Rows: {analytics_df.duplicated().sum()}")

print("\nMissing Values:")
print(analytics_df.isnull().sum())

==================================================
MERGE VALIDATION
==================================================
Rows: 113425
Columns: 27

Unique Orders: 99441
Duplicate Rows: 0

Missing Values:
order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 161
order_delivered_carrier_date     1968
order_delivered_customer_date    3229
order_estimated_delivery_date       0
purchase_year                       0
purchase_month                      0
purchase_month_name                 0
purchase_day                        0
purchase_weekday                    0
purchase_hour                       0
purchase_quarter                    0
delivery_time_days               3229
delivery_delay_days              3229
customer_unique_id                  0
customer_zip_code_prefix            0
customer_city                       0
customer_state                      0
order_item_id                     775
product_id                        775
seller_id                         775
shipping_limit_date               775
price                             775
freight_value                     775
dtype: int64

In [185]:
analytics_df[
    analytics_df["product_id"].isnull()
]["order_status"].value_counts()

order_status
unavailable    603
canceled       164
created          5
invoiced         2
shipped          1
Name: count, dtype: int64

In [186]:
orders_df[
    ~orders_df["order_id"].isin(order_items_df["order_id"])
]

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,purchase_year,purchase_month,purchase_month_name,purchase_day,purchase_weekday,purchase_hour,purchase_quarter,delivery_time_days,delivery_delay_days
266,8e24261a7e58791d10cb1bf9da94df5c,64a254d30eed42cd0e6c36dddb88adf0,unavailable,2017-11-16 15:09:28,2017-11-16 15:26:57,NaT,NaT,2017-12-05,2017,11,November,16,Thursday,15,4,NaN,NaN
586,c272bcd21c287498b4883c7512019702,9582c5bbecc65eb568e2c1d839b5cba1,unavailable,2018-01-31 11:31:37,2018-01-31 14:23:50,NaT,NaT,2018-02-16,2018,1,January,31,Wednesday,11,1,NaN,NaN
687,37553832a3a89c9b2db59701c357ca67,7607cd563696c27ede287e515812d528,unavailable,2017-08-14 17:38:02,2017-08-17 00:15:18,NaT,NaT,2017-09-05,2017,8,August,14,Monday,17,3,NaN,NaN
737,d57e15fb07fd180f06ab3926b39edcd2,470b93b3f1cde85550fc74cd3a476c78,unavailable,2018-01-08 19:39:03,2018-01-09 07:26:08,NaT,NaT,2018-02-06,2018,1,January,8,Monday,19,1,NaN,NaN
1130,00b1cb0320190ca0daa2c88b35206009,3532ba38a3fd242259a514ac2b6ae6b6,canceled,2018-08-28 15:26:39,NaT,NaT,NaT,2018-09-12,2018,8,August,28,Tuesday,15,3,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99252,aaab15da689073f8f9aa978a390a69d1,df20748206e4b865b2f14a5eabbfcf34,unavailable,2018-01-16 14:27:59,2018-01-17 03:37:34,NaT,NaT,2018-02-06,2018,1,January,16,Tuesday,14,1,NaN,NaN
99283,3a3cddda5a7c27851bd96c3313412840,0b0d6095c5555fe083844281f6b093bb,canceled,2018-08-31 16:13:44,NaT,NaT,NaT,2018-10-01,2018,8,August,31,Friday,16,3,NaN,NaN
99347,a89abace0dcc01eeb267a9660b5ac126,2f0524a7b1b3845a1a57fcf3910c4333,canceled,2018-09-06 18:45:47,NaT,NaT,NaT,2018-09-27,2018,9,September,6,Thursday,18,3,NaN,NaN
99348,a69ba794cc7deb415c3e15a0a3877e69,726f0894b5becdf952ea537d5266e543,unavailable,2017-08-23 16:28:04,2017-08-28 15:44:47,NaT,NaT,2017-09-15,2017,8,August,23,Wednesday,16,3,NaN,NaN
99415,5fabc81b6322c8443648e1b21a6fef21,32c9df889d41b0ee8309a5efb6855dcb,unavailable,2017-10-10 10:50:03,2017-10-14 18:35:57,NaT,NaT,2017-10-23,2017,10,October,10,Tuesday,10,4,NaN,NaN

In [187]:
analytics_df.columns

Index(['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp',
       'order_approved_at', 'order_delivered_carrier_date',
       'order_delivered_customer_date', 'order_estimated_delivery_date',
       'purchase_year', 'purchase_month', 'purchase_month_name',
       'purchase_day', 'purchase_weekday', 'purchase_hour', 'purchase_quarter',
       'delivery_time_days', 'delivery_delay_days', 'customer_unique_id',
       'customer_zip_code_prefix', 'customer_city', 'customer_state',
       'order_item_id', 'product_id', 'seller_id', 'shipping_limit_date',
       'price', 'freight_value'],
      dtype='object')

In [189]:
analytics_df = analytics_df.merge(
    products_df,
    on="product_id",
    how="left",
    validate="many_to_one"
)

In [190]:
print("="*50)
print("MERGE VALIDATION")
print("="*50)

print(f"Rows: {analytics_df.shape[0]}")
print(f"Columns: {analytics_df.shape[1]}")
print(f"Unique Orders: {analytics_df['order_id'].nunique()}")
print(f"Duplicate Rows: {analytics_df.duplicated().sum()}")

print("\nNew Missing Values:")
print(analytics_df[
    [
        "product_category_name",
        "product_weight_g",
        "product_length_cm",
        "product_height_cm",
        "product_width_cm"
    ]
].isnull().sum())

==================================================
MERGE VALIDATION
==================================================
Rows: 113425
Columns: 35
Unique Orders: 99441
Duplicate Rows: 0

New Missing Values:
product_category_name    2378
product_weight_g          793
product_length_cm         793
product_height_cm         793
product_width_cm          793
dtype: int64

In [191]:
analytics_df = analytics_df.merge(
    sellers_df,
    on="seller_id",
    how="left",
    validate="many_to_one"
)

In [192]:
print("="*50)
print("MERGE VALIDATION")
print("="*50)

print(f"Rows: {analytics_df.shape[0]}")
print(f"Columns: {analytics_df.shape[1]}")
print(f"Unique Orders: {analytics_df['order_id'].nunique()}")
print(f"Duplicate Rows: {analytics_df.duplicated().sum()}")

print("\nMissing Values:")
print(
    analytics_df[
        [
            "seller_id",
            "seller_zip_code_prefix",
            "seller_city",
            "seller_state"
        ]
    ].isnull().sum()
)

==================================================
MERGE VALIDATION
==================================================
Rows: 113425
Columns: 38
Unique Orders: 99441
Duplicate Rows: 0

Missing Values:
seller_id                 775
seller_zip_code_prefix    775
seller_city               775
seller_state              775
dtype: int64

In [193]:
payments_df.columns

Index(['order_id', 'payment_sequential', 'payment_type',
       'payment_installments', 'payment_value'],
      dtype='object')

In [194]:
payments_summary = (
    payments_df
    .groupby("order_id")
    .agg(
        total_payment=("payment_value", "sum"),
        payment_count=("payment_sequential", "count"),
        primary_payment_type=("payment_type", "first"),
        max_installments=("payment_installments", "max")
    )
    .reset_index()
)

In [195]:
payments_summary.head()

,order_id,total_payment,payment_count,primary_payment_type,max_installments
0,00010242fe8c5a6d1ba2dd792cb16214,72.19,1,credit_card,2
1,00018f77f2f0320c557190d7a144bdd3,259.83,1,credit_card,3
2,000229ec398224ef6ca0657da4fc703e,216.87,1,credit_card,5
3,00024acbcdf0a6daa1e931b038114c75,25.78,1,credit_card,2
4,00042b26cf59d7ce69dfabb4e55b4fd9,218.04,1,credit_card,3

In [196]:
payments_summary.rename(columns={
    "total_payment": "payment_amount",
    "payment_count": "no_of_payments",
    "primary_payment_type": "payment_method",
    "max_installments": "installments"
}, inplace=True)

In [197]:
analytics_df = analytics_df.merge(
    payments_summary,
    on="order_id",
    how="left",
    validate="many_to_one"
)

In [198]:
print(analytics_df.shape)
analytics_df[[
    "payment_amount",
    "payment_method",
    "installments"
]].isnull().sum()

(113425, 42)

payment_amount    3
payment_method    3
installments      3
dtype: int64

In [199]:
reviews_summary = (
    reviews_df
    .groupby("order_id")
    .agg(
        review_score=("review_score", "mean"),
        review_count=("review_id", "count"),
        review_creation=("review_creation_date", "min")
    )
    .reset_index()
)

In [200]:
analytics_df = analytics_df.merge(
    reviews_summary,
    on="order_id",
    how="left",
    validate="many_to_one"
)

In [201]:
print(analytics_df.shape)
analytics_df[[
    "review_score",
    "review_count"
]].isnull().sum()

(113425, 45)

review_score    961
review_count    961
dtype: int64

In [204]:
analytics_df = analytics_df.merge(
    category_translation_df,
    on="product_category_name",
    how="left",
    validate="many_to_one"
)

In [205]:
analytics_df.rename(
    columns={
        "product_category_name_english":"product_category"
    },
    inplace=True
)

In [206]:
print("="*60)
print("FINAL ANALYTICS DATASET")
print("="*60)

print("Shape :", analytics_df.shape)

print("\nDuplicate Rows :", analytics_df.duplicated().sum())

print("\nUnique Orders :", analytics_df["order_id"].nunique())

print("\nUnique Customers :", analytics_df["customer_unique_id"].nunique())

print("\nUnique Products :", analytics_df["product_id"].nunique())

print("\nUnique Sellers :", analytics_df["seller_id"].nunique())

============================================================
FINAL ANALYTICS DATASET
============================================================
Shape : (113425, 46)

Duplicate Rows : 0

Unique Orders : 99441

Unique Customers : 96096

Unique Products : 32951

Unique Sellers : 3095

In [207]:
analytics_df.to_csv("analytics_df.csv", index=False)

In [208]:
from google.colab import files
files.download("analytics_df.csv")